"""empty message

Revision ID: e3ab5bf5d6cf
Revises: ec350d1926b4
Create Date: 2022-02-07 17:44:59.957487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ab5bf5d6cf'
down_revision = 'ec350d1926b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'notes')
    # ### end Alembic commands ###
