"""empty message

Revision ID: ec350d1926b4
Revises: fe09b9474c53
Create Date: 2022-02-07 14:54:58.902280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec350d1926b4'
down_revision = 'fe09b9474c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financials', sa.Column('avgVolume', sa.Integer(), nullable=True))
    op.add_column('financials', sa.Column('netProScore', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financials', 'netProScore')
    op.drop_column('financials', 'avgVolume')
    # ### end Alembic commands ###
